<!-- body -->
<table class="body-wrap" bgcolor="#f6f6f6">
  <tr>
    <td></td>
    <td class="container" bgcolor="#FFFFFF">

      <!-- content -->
      <div class="content">
      <table>
        <tr>
          <td>
            <p>Hi there,</p>
            <p>You registered on CAP, please keep the following, as you will require them to make requests.</p>
            <h1>Your Access keys</h1>
            <p><strong>Public key:</strong> <?php echo $public_key;?></p>
            <p><strong>Private key:</strong> <?php echo $private_key;?></p>
            <p><strong>Your user id:</strong> <?php echo $user_id;?></p>
            <!-- button -->
            <table class="btn-primary" cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td>
                  <a href="https://github.com/pete314/cap-api">View the source and instructions on GitHub</a>
                </td>
              </tr>
            </table>
            <!-- /button -->
            <p>Thanks,</p>
          </td>
        </tr>
      </table>
      </div>
      <!-- /content -->
      
    </td>
    <td></td>
  </tr>
</table>
<!-- /body -->